export const ROLL_THE_DICE = "ROLL_THE_DICE";
export const MARK_PLAYER_AS_WIN = "MARK_PLAYER_AS_WIN";
export const DEQUE_FRONT_AND_PUSH_BACK = "DEQUE_FRONT_AND_PUSH_BACK";
export const DEQUE_FRONT = "DEQUE_FRONT";

export const UPDATE_DICE_AND_PLAYER_POINTS_AND_RANK = "UPDATE_DICE_AND_PLAYER_POINTS_AND_RANK";


export const SET_MESSAGE = "SET_MESSAGE";

export const HANDLE_DICE_ROLE = 'HANDLE_DICE_ROLE';
export const UPDATE_GAME_CONFIG = "UPDATE_GAME_CONFIG";

export const SET_PLAYER_QUEUE_AND_ORDERING_AND_PLAYERS = "SET_PLAYER_QUEUE_AND_ORDERING_AND_PLAYERS";
export const UPDATE_RANKS = "UPDATE_RANKS";
export const ADD_WON_PLAYER = "ADD_WON_PLAYER";
export const RESET_DATA = "RESET_DATA";
export const TOGGLE_VIEW_SUMMARY = "TOGGLE_VIEW_SUMMARY";


export const UPDATE_STATE = 'UPDATE_STATE';